version: '3.9'
services:
  etopo1-gmt6-bedrock:
    image:  jac18281828/bedrock:etopo1-gmt6-bedrock-${BEDROCK_BUILD_VERSION}
    network_mode: none    
    build:
      context: bedrock/      
      args: 
        - ETOPO_GRIDFILE=ETOPO1_Bed_g_gmt4.grd
        - ETOPO_SURFACE=bedrock
  etopo1-gmt6-ice-surface:
    image:  jac18281828/bedrock:etopo1-gmt6-ice-${BEDROCK_BUILD_VERSION}
    network_mode: none    
    build:
      context: bedrock/      
      args: 
        - ETOPO_GRIDFILE=ETOPO1_Ice_g_gmt4.grd
        - ETOPO_SURFACE=ice_surface        
