version: '3.9'
services:
  bedrock-latest:
    image: jac18281828/bedrock
    build:
      context: bedrock/      
      args: 
        - ETOPO_GRIDFILE=ETOPO1_Bed_g_gmt4.grd
        - ETOPO_URL=https://ngdc.noaa.gov/mgg/global/relief/ETOPO1/data/bedrock/grid_registered/netcdf/ETOPO1_Bed_g_gmt4.grd.gz
  etopo1-gmt6-bedrock:
    image:  jac18281828/bedrock-etopo1-gmt6:${BEDROCK_BUILD_VERSION}
    build:
      context: bedrock/      
      args: 
        - ETOPO_GRIDFILE=ETOPO1_Bed_g_gmt4.grd
        - ETOPO_URL=https://ngdc.noaa.gov/mgg/global/relief/ETOPO1/data/bedrock/grid_registered/netcdf/ETOPO1_Bed_g_gmt4.grd.gz
  ice-latest:
    image: jac18281828/ice
    build:
      context: bedrock/      
      args: 
        - ETOPO_GRIDFILE=ETOPO1_Ice_g_gmt4.grd
        - ETOPO_URL=https://ngdc.noaa.gov/mgg/global/relief/ETOPO1/data/ice_surface/grid_registered/netcdf/ETOPO1_Ice_g_gmt4.grd.gz
  etopo1-gmt6-bedrock:
    image:  jac18281828/ice-etopo1-gmt6:${BEDROCK_BUILD_VERSION}
    build:
      context: bedrock/      
      args: 
        - ETOPO_GRIDFILE=ETOPO1_Ice_g_gmt4.grd
        - ETOPO_URL=https://ngdc.noaa.gov/mgg/global/relief/ETOPO1/data/ice_surface/grid_registered/netcdf/ETOPO1_Ice_g_gmt4.grd.gz

        
