version: '3.9'
services:
  etopo-2022-30s-bedrock:
    image:  jac18281828/bedrock:etopo-2022-30s-gmt6-bedrock-${VERSION}
    network_mode: none    
    build:
      context: bedrock/      
      args:
        - ETOPO_RES=30s
        - ETOPO_GRIDFILE=ETOPO_2022_v1_30s_N90W180_bed.nc
        - ETOPO_SURFACE=bed
  etopo-30s-2022-ice-surface:
    image:  jac18281828/bedrock:etopo-2022-30s-gmt6-ice-${VERSION}
    network_mode: none    
    build:
      context: bedrock/      
      args:
        - ETOPO_RES=30s        
        - ETOPO_GRIDFILE=ETOPO_2022_v1_30s_N90W180_surface.nc
        - ETOPO_SURFACE=surface
