name: Docker Image CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "*"
    
jobs:
  dockerimage:
    strategy:
      matrix:
        surface: [bed, surface]
        res: [30s]
        version: [v1]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: bedrock/
          platforms: linux/amd64, linux/arm64
          push: false
          build-args: |
            ETOPO_RES=${{ matrix.res }}
            ETOPO_VERSION=${{ matrix.version }}
            ETOPO_SURFACE=${{ matrix.surface }}
            VERSION=latest

