name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}        
    - name: Build the Docker image
      run: |
        export BEDROCK_BUILD_VERSION=$(date +%m%d%y)
        docker-compose build
    - name: Push the images
      run:
        export BEDROCK_BUILD_VERSION=$(date +%m%d%y)        
        docker-compose push
      if: ${{ github.event_name == 'release' && github.event.action == 'created' }}

