name: Docker Image Build Push CI

on:
  push:
    tags:
      - "*"

concurrency:
  group: "docker-image"
  cancel-in-progress: true
    
jobs:
  dockerimage:
    strategy:
      matrix:
        surface: [bed, surface]
        res: [30s]
        version: [v1]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate repository name
        run: |
          echo "REPOSITORY_PATH=$( echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]' )" >> ${GITHUB_ENV}
          echo "REPOSITORY_SHA=$( echo ${GITHUB_SHA} | cut -c 1-8 )" >> ${GITHUB_ENV}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: bedrock/
          platforms: linux/amd64, linux/arm64
          push: true
          build-args: |
            ETOPO_RES=${{ matrix.res }}
            ETOPO_VERSION=${{ matrix.version }}
            ETOPO_SURFACE=${{ matrix.surface }}
            VERSION=${{ github.event.release.tag_name }}            
          tags: |
            ${{ env.REPOSITORY_PATH }}:${{ matrix.surface }}-${{ matrix.res }}-v${{ github.event.release.tag_name }}
            ${{ env.REPOSITORY_PATH }}:${{ matrix.surface }}-${{ matrix.res }}-${{ env.REPOSITORY_SHA }}
            ${{ env.REPOSITORY_PATH }}:${{ matrix.surface }}-${{ matrix.res }}
            ${{ env.REPOSITORY_PATH }}:${{ matrix.surface }}
            ghcr.io/${{ env.REPOSITORY_PATH }}:${{ matrix.surface }}-${{ matrix.res }}-v${{ github.event.release.tag_name }}
            ghcr.io/${{ env.REPOSITORY_PATH }}:${{ matrix.surface }}-${{ matrix.res }}-${{ env.REPOSITORY_SHA }}
            ghcr.io/${{ env.REPOSITORY_PATH }}:${{ matrix.surface }}-${{ matrix.res }}
            ghcr.io/${{ env.REPOSITORY_PATH }}:${{ matrix.surface }}
  
