name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

concurrency:
  group: "docker-image"
  cancel-in-progress: true
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and Push
        run: |
          export BEDROCK_BUILD_VERSION=$( echo ${GITHUB_SHA} | cut -c 1-8 )-arm64
          COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 DOCKER_DEFAULT_PLATFORM=linux/arm64/v8 docker compose build && DOCKER_DEFAULT_PLATFORM=linux/arm64/v8 docker compose push          
          export BEDROCK_BUILD_VERSION=$( echo ${GITHUB_SHA} | cut -c 1-8 )
          COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 DOCKER_DEFAULT_PLATFORM=linux/amd64 docker compose build && DOCKER_DEFAULT_PLATFORM=linux/amd64 docker compose push
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
