name: Docker Image Build Push CI

on:
  push:
    tags:
      - "*"

concurrency:
  group: "docker-image"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
          name: GitHub Release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              draft: false
              prerelease: false        
              tag_name: ${{ github.ref }}
              release_name: ${{ github.ref }}
              body_path: CHANGELOG.md
